#!/bin/bash

 z80asm -i 4DTICTAC.ASM -o 4DTICTAC.COM
 z80asm -i AMBUSH.ASM -o AMBUSH.COM
 z80asm -i AMBUSH1.ASM -o AMBUSH2.COM
 z80asm -i CHASE.ASM -o CHASE.COM
 z80asm -i DAZCHESS.ASM -o DAZCHESS.COM
 z80asm -i DOGFIGHT.ASM -o DOGFIGHT.COM --list=DOGFIGHT.LST
 z80asm -i DOODLE.ASM -o DOODLE.COM
 z80asm -i GOTCHA.ASM -o GOTCHA.COM --list=GOTCHA.LST
 z80asm -i LIFE.ASM -o LIFE.COM
 z80asm -i MARTINI.ASM -o MARTINI.COM
 z80asm --list=SPACEWAR.LST -i SPACEWAR.ASM -o SPACEWAR.COM
 z80asm --list=TANKWAR.LST -i TANKWAR.ASM -o TANKWAR.COM
 z80asm -i TRACK.ASM -o TRACK.COM
 z80asm -i X-LIFE.ASM -o X-LIFE.COM



 
