#!/bin/bash

 z80asm -i 4DTICTAC.ASM -o 4DTICTAC.COM --list=4DTICTAC.LST
 z80asm -i AMBUSH.ASM -o AMBUSH.COM --list=AMBUSH.LST
 z80asm -i AMBUSH2.ASM -o AMBUSH2.COM --list=AMBUSH2.LST
 z80asm -i CHASE.ASM -o CHASE.COM --list=CHASE.LST
 z80asm -i DAZCHESS.ASM -o DAZCHESS.COM --list=DAZCHESS.LST
 z80asm -i DOGFIGHT.ASM -o DOGFIGHT.COM --list=DOGFIGHT.LST
 z80asm -i DOGFIGHT2.ASM -o DOGFIGHT2.COM --list=DOGFIGHT2.LST
 z80asm -i DOODLE.ASM -o DOODLE.COM --list=DOODLE.LST
 z80asm -i GOTCHA.ASM -o GOTCHA.COM --list=GOTCHA.LST
 z80asm -i LIFE.ASM -o LIFE.COM --list=LIFE.LST
 z80asm -i MARTINI.ASM -o MARTINI.COM --list=MARTINI.LST
 z80asm --list=SPACEWAR.LST -i SPACEWAR.ASM -o SPACEWAR.COM
 z80asm --list=TANKWAR.LST -i TANKWAR.ASM -o TANKWAR.COM
 z80asm -i TRACK.ASM -o TRACK.COM --list=TRACK.LST
 z80asm -i X-LIFE.ASM -o X-LIFE.COM --list=X-LIFE.LST



 
