


	.Z80		;Z80 CODE USED
	.PHEX		;DDT COMPATIBLE
	.PABS
	.XLINK
	.XSYM		;NO SYMBOL TABLE
	.LOC	100H	;CP/M COMPATIBLE

FALSE	==	0H	;TRUE AND FALSE VALUES
TRUE	==	#FALSE
Z3S	==	TRUE	;THIS VERSION FOR THE Z3S BOARD
;MLIST	==	FALSE	;MACRO EXPANSION FLAG
MLIST	==	TRUE	;MACRO EXPANSION FLAG

BDOS	==	5
CR	==	13
LF	==	10
CONTLC	==	3	;<CONTROL-C> CHAR
BELL	==	7
CLEAR	==	26	;ZEUS80 CLEAR SCREEN

DBWAIT  ==      7       ;WAIT BIT
DBSIDE  ==      4       ;SIDE SELECT BIT
DCMD8S  ==      0F0H    ;8", SING DENS, SIDE 0, NO WAIT
DCMD8D  ==      0B0H    ;8", DOUB DENS, SIDE 0, NO WAIT
DCMD5S  ==      0D0H    ;5", SING DENS, SIDE 0, NO WAIT
DCMD5D  ==      90H     ;5", DOUB DENS, SIDE 0, NO WAIT

; FDC PORTS

DCMD	==	53H
W	==	054H	;WDC 179X PORTS
WCMD	==	W+0	;COMMAND REG
WSTAT	==	W+0	;STATUS REG
WTRACK	==	W+1	;TRACK REG
WSECT	==	W+2	;SECTOR REG
WDATA	==	W+3	;DATA I/O PORT

WFCINT	==	0D0H	;FORCED INTERRUPT COMMAND
SSEEK	==	1BH	;A REALLY SLOW SEEK COMMAND

;***************************************************
;          COMMON 179X COMMANDS/STATUS
;***************************************************

WSTIN	==	01011011B ;STEP IN
WHOMEF	==	00001011B ;HOME
WWRTRK	==	11110100B ;WRITE TRACK
WWRIT	==	10100000B ;WRITE SECTOR	

WSSTIN	==	10011100B ;STEP IN STATUS
WSHOME	==	10011100B ;HOME STATUS
WSWRTR	==	11100100B ;WRITE TRACK STATUS
WSWRIT	==	11111100B ;WRITE SECTOR STATUS

WBTRK0	==	2
WBBUSY	==	0


FORMAT:
	LXI	SP,100H	;VALIDATE THE STACK POINTER

LOOP:

	MVI		A,1
	STA		SEKTRAK
	STA		SEKSEC
	MVI		A,2
	STA		SEKDSK



	JMP LOOP

SEKDSK:	.BLKB	1
SEKTRK:	.BLKB	2
SEKSEC:	.BLKB	2

	
	.END





